# Generated by Django 2.2.2 on 2019-06-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models.host
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comments', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HdVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', netfields.fields.InetAddressField(blank=True, help_text='Updated automatically from primary Nic', max_length=39, null=True)),
                ('serial_no', models.CharField(max_length=30)),
                ('asset_no', models.CharField(max_length=30)),
                ('hypervisor', models.BooleanField(help_text='Does this machine contain VMs?')),
                ('details', models.CharField(blank=True, max_length=120)),
                ('lastseen', models.DateTimeField(blank=True, help_text='Updated automatically from primary Nic/LabScan', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('retired', 'Retired'), ('on_loan', 'On Loan'), ('unknown', 'Unknown')], default=inventory.models.host.HostStatus('Unknown'), help_text="Changing this from Active will automatically suspend this host's bookable if there is an active one.", max_length=30)),
                ('diskvendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.HdVendor')),
                ('group', models.ForeignKey(blank=True, help_text='Limit bookings of this host to a specific group', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('network', netfields.fields.CidrAddressField(max_length=43)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='inventory.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=30, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('mac', netfields.fields.MACAddressField()),
                ('integrated', models.BooleanField()),
                ('management', models.BooleanField()),
                ('ip', netfields.fields.InetAddressField(blank=True, max_length=39, null=True)),
                ('primary', models.BooleanField(help_text='Is this the primary NIC in the assigned host?')),
                ('lastseen', models.DateTimeField(blank=True, help_text='Updated automatically from primary LabScan', null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='inventory.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(blank=True, max_length=120)),
                ('host_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hardwares', to='inventory.HostType')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.HostHardware'),
        ),
        migrations.AddField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/has been assigned to manage this machine', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Rack'),
        ),
        migrations.AddField(
            model_name='host',
            name='vm_host',
            field=models.ForeignKey(blank=True, help_text='Parent host if this host is virtualized', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Host'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=120)),
                ('asset_no', models.CharField(max_length=30)),
                ('cardtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.CardType')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='inventory.Host')),
            ],
        ),
    ]
