# Generated by Django 2.2.2 on 2019-06-18 13:10

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190618_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='network',
            field=netfields.fields.CidrAddressField(blank=True, max_length=43, null=True),
        ),
    ]
