# Generated by Django 2.2.2 on 2019-06-19 14:17

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190618_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='hypervisor',
            field=models.BooleanField(default=False, help_text='Does this machine contain VMs?'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('retired', 'Retired'), ('on_loan', 'On Loan'), ('unknown', 'Unknown')], default='unknown', help_text="Changing this from Active will automatically suspend this host's bookable if there is an active one.", max_length=30),
        ),
        migrations.AlterField(
            model_name='nic',
            name='mac',
            field=netfields.fields.MACAddressField(unique=True),
        ),
    ]
