# Generated by Django 2.2.2 on 2019-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190619_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='integrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nic',
            name='management',
            field=models.BooleanField(default=False),
        ),
    ]
