# Generated by Django 2.2.2 on 2019-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190620_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('retired', 'Retired'), ('on_loan', 'On Loan'), ('unknown', 'Unknown'), ('offline', 'Offline'), ('new', 'New')], default='new', help_text="Changing this from Active will automatically suspend this host's bookable if there is an active one.", max_length=30),
        ),
    ]
