# Generated by Django 2.2.2 on 2019-06-20 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20190620_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
