# Generated by Django 2.2.2 on 2019-06-25 13:52

from django.db import migrations, models
import django.db.models.deletion
import live.models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20190620_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationscanconflict',
            name='nsc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='live.NicScanConflict'),
        ),
        migrations.AlterField(
            model_name='scanconflict',
            name='scan',
            field=models.ForeignKey(on_delete=live.models.NON_POLYMORPHIC_CASCADE, related_name='conflicts', to='live.ScanSession'),
        ),
    ]
