# Generated by Django 2.2.2 on 2019-06-25 15:09

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20190625_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownScanConflict',
            fields=[
                ('scanconflict_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='live.ScanConflict')),
                ('ip', netfields.fields.InetAddressField(max_length=39)),
                ('mac', netfields.fields.MACAddressField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('live.scanconflict',),
        ),
        migrations.AlterField(
            model_name='nicscanconflict',
            name='newip',
            field=netfields.fields.InetAddressField(max_length=39, null=True),
        ),
    ]
