# Generated by Django 2.2.2 on 2019-06-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190620_1202'),
        ('live', '0005_auto_20190625_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownscanconflict',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Lab'),
        ),
    ]
