# Generated by Django 2.2.2 on 2019-07-16 10:57

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190704_0847'),
        ('live', '0006_unknownscanconflict_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationscanconflict',
            name='newlab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Lab'),
        ),
        migrations.AlterField(
            model_name='locationscanconflict',
            name='nsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='live.NicScanConflict'),
        ),
        migrations.CreateModel(
            name='VirtualHostsScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('old', 'Old'), ('ignore', 'Ignored'), ('super', 'Superseded')], default='active', max_length=8)),
                ('ip', netfields.fields.InetAddressField(max_length=39)),
                ('mac', netfields.fields.MACAddressField()),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Lab')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtualhosts', to='live.ScanSession')),
            ],
        ),
    ]
