# Generated by Django 2.2.2 on 2019-07-16 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190704_0847'),
        ('live', '0008_virtualhostsscan_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualhostsscan',
            name='lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='OfflineHostWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('resolved', 'Resolved'), ('ignore', 'Ignored'), ('super', 'Superseded')], default='new', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Host')),
            ],
        ),
    ]
