# Generated by Django 2.2.2 on 2019-07-16 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_auto_20190716_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownscanconflict',
            name='lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
