# Generated by Django 2.2.2 on 2019-07-18 11:05

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_unknownscanconflict_lastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredMacs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', netfields.fields.MACAddressField()),
                ('reason', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
