# Generated by Django 2.2.2 on 2019-07-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0011_ignoredmacs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IgnoredMacs',
            new_name='IgnoredMac',
        ),
    ]
