# Generated by Django 2.2.2 on 2019-07-05 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_auto_20190704_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_role', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('internal_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='When was this loan supposed to start?')),
                ('due_return', models.DateTimeField(help_text='When are we expecting this to be back?')),
                ('returned_date', models.DateTimeField(blank=True, help_text='When did this actually get back to us?', null=True)),
                ('returned', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Customer')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.Host')),
                ('user', models.ForeignKey(help_text='Individual responsible for the loan', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
