# Generated by Django 2.2.2 on 2019-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
