# Generated by Django 2.2.2 on 2019-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookable_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mail_end_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='mail_reminder_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mail_last_nag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mail_reminder_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
