# Generated by Django 2.2.2 on 2019-06-25 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190625_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mail_reminder_sent',
            new_name='mail_start_reminder_sent',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='mail_reminder_sent',
            new_name='mail_start_reminder_sent',
        ),
        migrations.AddField(
            model_name='booking',
            name='mail_end_reminder_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mail_end_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mail_last_nag',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
