# Generated by Django 2.2.2 on 2019-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190625_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='import_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
