# Generated by Django 2.2.2 on 2019-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='import_id',
            field=models.IntegerField(blank=True, help_text='ID from import source', null=True),
        ),
    ]
